### ISSUE TITLE
Pango problems with smaller fonts

### ISSUE THREAD

**Issue by mwlidar** [JuliaGraphics/Cairo.jl#349]
Since a few day smaller fonts (below 16pt) are not rendered correctly any more. Most easyly to see with the sample_pango_text.jl example:
![sample_pango_text](https://user-images.githubusercontent.com/87604697/144637779-ffaf0719-d409-4747-a06e-be435bc80f32.png)

This is with Julia 1.6.4 and Cairo 1.0.5. Must have to do with the lates FreeType package updates. But I wasn't able to narrow this down further...

**Comment by hustf** [comment]
It seems this affects all font scaling in Pango. If that is the case, a new version ought to be coming soon.

```text(cr,16.0,104.0,"Text<b>Bold</b><i>Italic</i><big>super-2</big>",markup=true)```

Confirmed on Windows, Julia 0.7.0.

```
julia> libpango_version = unsafe_string(
             ccall((:pango_version_string,Cairo.libpango),Cstring,()) )
"1.47.0"
```

**Comment by hustf** [comment]
Another example, indirectly to Cairo using Luxor. Font scaling is broken (with my setup).
It would be nice to know if this is an issue with the windows version, only? 

´´´
using Luxor
Drawing(640, 480, "temp.svg")
settext("Before, ϕ", Point(100.0, 150.0))
setfont("Georgia Bold", 65.0)
settext("Before, ϕ", Point(100.0, 200.0))
finish()
preview()
´´´

In case issues get posted at Luxor.jl, for info: @cormullion

**Comment by hustf** [comment]
'One size per font family per session' is close to describing the issue here.

It's daunting that the error remains until the next Julia session. Also, is this an issue on Windows only?

![sample_pango_text2a](https://user-images.githubusercontent.com/13949620/145845073-b4b218b0-978b-4be2-ae44-ccce892888a1.png)

![sample_pango_text2b](https://user-images.githubusercontent.com/13949620/145845141-fad20dc6-509a-4434-b8de-8e5d7e708cf0.png)

´´´
using Cairo
c = CairoRGBSurface(256,256);
cr = CairoContext(c);
fill(cr);
set_source_rgb(cr,0.8,0.8,0.8);    # light gray
set_font_face(cr, "Sans 16.0")

text(cr,40.0,60.0,"Sans 16.0")
text(cr,40.0,80.0,"Sans 16<small>small</small>",markup=true)
set_font_face(cr, "Sans 10.0")
text(cr,40.0,100.0,"Sans 10")
set_font_face(cr, "Sans 16")
text(cr,40.0,120.0,"Sans 16 again")

set_font_face(cr, "Serif 15.0")
text(cr,40.0,140.0,"Serif 15.0")

set_font_face(cr, "Serif 16.0")
text(cr,40.0,160.0,"Serif 16.0")

set_font_face(cr, "Cambria 12.0")
text(cr,40.0,180.0,"Cambria 12.0")

set_font_face(cr, "Cambria 15.0")
text(cr,40.0,200.0,"Cambria 15.0")

set_font_face(cr, "Serif 12.0")
text(cr,40.0,220.0,"Serif 12.0")

set_font_face(cr, "Serif 15.0")
text(cr,40.0,240.0,"Serif 15.0")

set_font_face(cr, "Sans 15.0")
text(cr,40.0,260.0,"Sans 15.0")

write_to_png(c,"sample_pango_text2a.png")
c = CairoRGBSurface(256,256);
cr = CairoContext(c);

fill(cr);
set_source_rgb(cr,0.8,0.8,0.8);    # light gray

set_font_face(cr, "Sans 12.0")
text(cr,40.0,60.0,"Sans 12")

set_font_face(cr, "Sans 16")
text(cr,40.0,80.0,"Sans 16 still special")

set_font_face(cr, "Cambria 15.0")
text(cr,40.0,100.0,"One size family quota!")

set_font_face(cr, "Cambria 12.0")
text(cr,40.0,120.0,"Cambria 12.0")

write_to_png(c,"sample_pango_text2b.png")

´´´

**Comment by giordano** [comment]
> Must have to do with the lates FreeType package updates.

What FreeType package are you talking about?  None of [`FreeType.jl`](https://github.com/JuliaGraphics/FreeType.jl) (which isn't used by this package) and [`FreeType2_jll.jl`](https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl) has been touched in the last 7 months.

**Comment by cormullion** [comment]
FYI, your code on MacOS:

![sample_pango_text2a](https://user-images.githubusercontent.com/52289/145859642-84cbe66c-b6d4-4c91-9b90-aeed114d35af.png)

![sample_pango_text2b](https://user-images.githubusercontent.com/52289/145859639-9e3534f6-c535-4612-bcc5-7e574af27ca0.png)

**Comment by hustf** [comment]
Pango_jll is at version 1.47. Let's try the previous:

```
(Cairo) pkg> pin Pango_jll@v1.42.4
  [36c8627f] ↓ Pango_jll v1.47.0+0 ⇒ v1.42.4+10 ⚲
..code from above...
```
![sample_pango_text2a](https://user-images.githubusercontent.com/13949620/146034563-2f32125c-2bdd-4613-9629-321053d8f3cc.png)
![sample_pango_text2b](https://user-images.githubusercontent.com/13949620/146034578-301178bb-42d9-473b-ae1c-c65b0a6fd5a8.png)

So we found the culprit. All the while, there's a Pango version 1.49.4. I haven't found any relevant issues, but some large changes came between 1.43 and 1.44. Particularly, font size is now not stored with the other font attributes.

We just culpritted Pango. How does one go about requesting an updated Pango_jll compilation? I found no relevant [issues](https://gitlab.gnome.org/GNOME/pango/-/issues), but one can hope this is fixed by now?

**Comment by mwlidar** [comment]
Now Pango_jll is at version 1.50.3 but the problem is still there for me (on Windows with Julia 1.6.5 and 1.7.2). Pinning Pango_jll to 
1.42.4 still solves the problem. Is this a general issue for Windows are is this biting only a few, depending on their installation?

**Comment by ma-laforge** [comment]
Problem persists with Julia v1.8.2 & Pango_jll v1.50.9 on Windows.

Though the font sizes that cause issues are different than those reported by @hustf :

![image](https://user-images.githubusercontent.com/11205411/197368268-cb1640af-aea9-43a3-b7d4-7182dfa0a5f7.png)
![image](https://user-images.githubusercontent.com/11205411/197368275-93c5658e-f3a6-475a-8b5c-ba31183b5955.png)

**Comment by ma-laforge** [comment]
Downgrading Pango_jll 1.50.3 --> v1.42 still worked to get fonts rendered correctly on my system (as @hustf mentioned):

```julia
⌃ [77ec8976] ↓ GTK3_jll v3.24.31+0 ⇒ v3.24.29+0
  [57eb2189] + Libcroco_jll v0.6.13+2
⌃ [925c91fb] ↓ Librsvg_jll v2.52.4+0 ⇒ v2.42.2+3
⌃ [36c8627f] ↓ Pango_jll v1.50.9+0 ⇒ v1.42.4+10
```

Though downgrading Pango downgrades 2 dependent packages (and adds Libcroco_jll).

**Comment by hustf** [comment]
"Downgrading" dependencies seems the best choice right now, just from looking at the maintenance history. Or are jlls upgrade 

 The whole jll system is a mystery to me, but I  encourage somebody with the skills or curiosity to step in.  

Cairo on Windows has more than a few uses,  though the dependencies usually get the credit.

**Comment by jwahlstrand** [comment]
Seems to be fixed by updating HarfBuzz_jll to 8.3.1. Can anyone confirm?

**Comment by hustf** [comment]
I confirm. And send my best regards!

In Windows, a fresh environment, Julia 1.10.4:

´´´
(@Cairo) pkg> add Cairo
...
  [2e76f6c2] + HarfBuzz_jll v8.3.1+0
...


[code from above](https://github.com/JuliaGraphics/Cairo.jl/issues/349#issuecomment-992624668)

![sample_pango_text2a](https://github.com/user-attachments/assets/345926a0-e818-45f7-9e2b-fe7cd5427a6f)
![sample_pango_text2b](https://github.com/user-attachments/assets/20c3c37c-7917-4099-b7de-e17ad82e5b78)
